spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://121.42.13.136:6603/daily-coorder"
    username: test
    password: 159357@test
    hikari:
      maxLifetime: 20000

server:
  port: ${port:8080}


spring.servlet.miltipart.maxFileSize: 10MB
spring.servlet.miltipart.maxRequestSize: 10MB


  # jwt서명키
  jwt.signing.key.secret=mySecret
  
  # 토큰 인증 URI
  jwt.get.token.uri=/authenticate
  
  # 토큰 갱신 URI
  jwt.refresh.token.uri=/refresh
  
  # 토큰 전송하는 http 헤더 이름
  jwt.http.request.header=Authorization
  
  # 토큰 만료 시간 (1일)
  jwt.token.expiration.in.seconds=86400
  
  # 토큰을 담을 쿠키 이름
  token.cookie.name=token
  
  # 쿠키 만료 시간 (1일)
  token.cookie.expiration.in.seconds=86400