spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: "jdbc:mysql://121.42.13.136:6603/"
    username: test
    password: 159357@test
    hikari:
      maxLifetime: 20000

server:
  port: ${port:8080}